[compression]
level = 6
max_workers = 2
strip_metadata = true
optimize_alpha = false
fast_evaluation = false

[logging]
show_progress = true
show_file_sizes = true
show_summary = true
verbose_logging = false

[advanced]
custom_filters = ["None", "Sub", "Up", "Average", "Paeth"]
deflate_method = "libdeflate"
deflate_level = 12
interlace = "None"
